#!/usr/bin/php
<?php

echo "*** Installing Cowl.\n";

echo "** Moving app-directory\n";

# Move sample app directory
if ( ! is_dir('../app/') )
{
	shell_exec("cp -R app-SAMPLE/ ../app/");
}

echo "** Moving .htaccess\n";

# Move .htaccess and index.php
if ( ! file_exists('../.htaccess') )
{
	shell_exec("SAMPLE.htaccess ../.htaccess");

	# Change RewriteBase / to the real base
	echo "# Please enter the base web path of your app (almost always /): \n";

	$BASE_PATH = trim(fgets(STDIN));

	file_put_contents("../.htaccess", str_replace("RewriteBase /", "RewriteBase $BASE_PATH", file_get_contents("../.htaccess")));
}

echo "** Moving index.php\n";

if ( ! file_exists('../index.php') )
{
	shell_exec("cp index.php-SAMPLE ../index.php");
}

# Make /cowl/cache writeable
shell_exec("mkdir cache");
shell_exec("chmod 0777 ./cache");

echo "*** Done.\n";
