<?php

define('COWL_TEST_PATH', dirname(__FILE__) . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR);
define('COWL_TEST_APP', dirname(__FILE__) . DIRECTORY_SEPARATOR . 'app/' . DIRECTORY_SEPARATOR);
